# Generated by Django 5.2.4 on 2025-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=200)),
                ('video_len', models.CharField(max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('tag', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
