



# Generated by Django 5.1.6 on 2025-03-28 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=3)),
                ('last_seen', models.DateTimeField(verbose_name='2025-03-28')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.topics')),
            ],
        ),
    ]
