



# Generated by Django 5.1.6 on 2025-03-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0003_subtopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopics',
            name='last_seen',
            field=models.DateTimeField(verbose_name='2025-03-30'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='rating',
            field=models.FloatField(default=3, max_length=5),
        ),
    ]
