



# Generated by Django 5.1.6 on 2025-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0004_alter_subtopics_last_seen_alter_topics_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='rating',
            field=models.FloatField(default=3, max_length=1),
        ),
    ]
