



# Generated by Django 5.1.6 on 2025-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0007_alter_subjects_rating_alter_subtopics_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopics',
            name='last_seen',
            field=models.DateTimeField(verbose_name='2025-03-31'),
        ),
    ]
