# Generated by Django 5.1.6 on 2025-04-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0010_alter_subtopics_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopics',
            name='last_seen',
            field=models.DateTimeField(verbose_name='2025-04-13'),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic', to='Subjects.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='Subjects.subjects'),
        ),
    ]
