# Generated by Django 5.2 on 2025-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0011_alter_subtopics_last_seen_alter_subtopics_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopics',
            name='last_seen',
            field=models.DateTimeField(verbose_name='2025-04-16'),
        ),
    ]
