



# Generated by Django 5.2 on 2025-04-24 21:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0013_alter_subtopics_last_seen_usertopicmemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopics',
            name='last_seen',
            field=models.DateTimeField(verbose_name='2025-04-24'),
        ),
        migrations.CreateModel(
            name='SubTopicMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_strength', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=1)),
                ('next_review', models.DateField(default=datetime.date.today)),
                ('revison_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subtopics')),
            ],
        ),
        migrations.DeleteModel(
            name='UserTopicMemory',
        ),
    ]
