



# Generated by Django 5.2 on 2025-04-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0014_alter_subtopics_last_seen_subtopicmemory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopicmemory',
            old_name='revison_count',
            new_name='revision_count',
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='last_seen',
            field=models.DateTimeField(verbose_name='2025-04-25'),
        ),
    ]
