# Generated by Django 5.2 on 2025-04-30 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0016_alter_subtopics_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicmemory',
            name='next_review',
            field=models.DateField(default=datetime.date(2025, 4, 30)),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='last_seen',
            field=models.DateTimeField(verbose_name='2025-04-30'),
        ),
        migrations.AlterUniqueTogether(
            name='subtopics',
            unique_together={('subtopic_name', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='topics',
            unique_together={('topic_name', 'subject')},
        ),
    ]
