# Generated by Django 5.2 on 2025-05-03 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0017_alter_subtopicmemory_next_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicmemory',
            name='next_review',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='last_seen',
            field=models.DateTimeField(verbose_name='2025-05-03'),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='Subjects.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='Subjects.subjects'),
        ),
        migrations.CreateModel(
            name='SubtopicEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic', to='Subjects.subtopics')),
            ],
        ),
    ]
