



# Generated by Django 5.2 on 2025-05-05 05:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0018_alter_subtopicmemory_next_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopicentry',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subtopicentry',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicentry', to='Subjects.subtopics'),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subtopics',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic', to='Subjects.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='Subjects.subjects'),
        ),
    ]
