



# Generated by Django 5.2 on 2025-05-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0019_subtopicentry_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopics',
            name='review',
            field=models.BooleanField(default=True),
        ),
    ]
